GET http://localhost:8082/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJLaW0iLCJleHAiOjE2NzEwMzczMTV9.FdTm2X7PLA6Fl3g2eN6XVgA_UAF0oUr19lsFz6CxakA