GET http://localhost:8082/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJLaW0iLCJleHAiOjE2NzEwODAwODV9.aDZt83QOABIBAjYkJ5yHrIRy9XjrKSWulYH6thXQI-c